const fs=require('fs'),T=require('three');
if(!process.argv[2]) throw new Error('Usage: node scripts/prepare-heart.cjs <path-to-cardiovascular.glb>; source and licence: public/medical/ANATOMY-CREDITS.txt');
const src=fs.readFileSync(process.argv[2]),n=src.readUInt32LE(12),j=JSON.parse(src.subarray(20,20+n));
const names=['Right atrium','Left atrium','Right ventricle','Left ventricle','Ascending aorta','Aortic arch','Pulmonary trunk','Left pulmonary artery','Right pulmonary artery'];
const selected=j.nodes.map((node,i)=>({node,i,name:node.name.replace(/\.001$/,'')})).filter(x=>names.includes(x.name));
const bounds=new T.Box3(),labels=[];
for(const {node,name} of selected){const local=new T.Box3();for(const p of j.meshes[node.mesh].primitives){const a=j.accessors[p.attributes.POSITION];local.union(new T.Box3(new T.Vector3(...a.min),new T.Vector3(...a.max)));}const m=new T.Matrix4().compose(new T.Vector3(...(node.translation||[0,0,0])),new T.Quaternion(...(node.rotation||[0,0,0,1])),new T.Vector3(...(node.scale||[1,1,1])));local.applyMatrix4(m);bounds.union(local);labels.push({name,position:local.getCenter(new T.Vector3()).toArray()});}
const center=bounds.getCenter(new T.Vector3());labels.forEach(l=>l.position=l.position.map((v,i)=>v-center.toArray()[i]));
j.nodes.push({name:'Quasar heart selection',translation:center.toArray().map(v=>-v),children:selected.map(x=>x.i)});j.scenes=[{name:'Heart and great vessels',nodes:[j.nodes.length-1]}];j.scene=0;j.asset.copyright='Z-Anatomy / BodyParts3D © DBCLS, CC BY-SA 4.0. GLB export Liyucheng1997; Quasar selected heart structures and centered model.';
let json=Buffer.from(JSON.stringify(j));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const rest=src.subarray(20+n),head=Buffer.alloc(20);head.writeUInt32LE(0x46546c67);head.writeUInt32LE(2,4);head.writeUInt32LE(20+json.length+rest.length,8);head.writeUInt32LE(json.length,12);head.writeUInt32LE(0x4e4f534a,16);fs.writeFileSync('public/medical/heart.glb',Buffer.concat([head,json,rest]));fs.writeFileSync('public/medical/heart-labels.json',JSON.stringify(labels,null,2));console.log({structures:labels.length,bounds:bounds.getSize(new T.Vector3()).toArray(),labels});
